language: php

php:
  - 7.4

sudo: false

before_install:
  - composer self-update
  - composer clear-cache

install:
  - travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-dist --prefer-stable

before_script:
  - cp config/config_test.yml config/config.yml

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
