language: php

php:
  - 8.1
  - 8.2
  - 8.3

sudo: false

before_install:
  - composer self-update
  - composer clear-cache

install:
  - travis_retry composer install --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-dist --prefer-stable

before_script:
  - cp config/config_test.yml config/config.yml

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
