#!/usr/bin/env php
<?php declare(strict_types=1);
// Installed via composer?
if (file_exists($a = __DIR__ . '/../../autoload.php')) {
    require_once $a;
} else {
    require_once __DIR__ . '/vendor/autoload.php';
}

use Access9\DbTableDump\Dump;

Dump::run(__DIR__ . '/config');
