services:
    config:
        class: "\\Access9\\DbTableDump\\Config"
    config_get:
        class: "\\Access9\\DbTableDump\\Console\\Command\\ConfigGetCommand"
    config_set:
        class: "\\Access9\\DbTableDump\\Console\\Command\\ConfigSetCommand"
    to_json:
        class: "\\Access9\\DbTableDump\\Console\\Command\\ToJsonCommand"
    to_yaml:
        class: "\\Access9\\DbTableDump\\Console\\Command\\ToYamlCommand"
    to_delimited:
        class: "\\Access9\\DbTableDump\\Console\\Command\\ToDelimitedCommand"
    to_xml:
        class: "\\Access9\\DbTableDump\\Console\\Command\\ToXmlCommand"
    application:
        class: "\\Access9\\DbTableDump\\Console\\Application"
        calls:
            - [add, ["@config_get"]]
            - [add, ["@config_set"]]
            - [add, ["@to_json"]]
            - [add, ["@to_yaml"]]
            - [add, ["@to_delimited"]]
            - [add, ["@to_xml"]]
            - [setConfig, ["@config"]]
